version: '3.3'
services:
  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:main
    ports:
      - "3101:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    restart: unless-stopped
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:main
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /tmp:/tmp
      - /home/${HOST_USER:-j}/.local/share/docker/containers:/var/log/containers:ro
      - /var/log/nginx:/var/log/nginx:ro
      - ./promtail-entrypoint.sh:/usr/bin/promtail-entrypoint.sh:ro
    command: -config.file=/etc/promtail/config.yml -log.level=info
    restart: unless-stopped
    depends_on:
      - loki
