- name: logs-app
  hosts: logs_app_host
  vars:
    remote_dir: "/home/{{ ansible_user }}/{{ domain }}/logs-app"
  tasks:
    - name: Ensure the destination directory exists
      file:
        path: "{{ remote_dir }}/grafana-provisioning/datasources"
        state: directory
        mode: '0755'

    - name: Ensure the directory mounted for promtail container exists
      file:
        path: /tmp/promtail
        state: directory
        mode: '0755'

    - name: Copy local app files to remote server
      synchronize:
        src: ./
        dest: "{{ remote_dir }}"
        delete: yes
        recursive: yes
        rsync_opts:
          - "--include=logs.yml"
          - "--include=promtail-config.yml"
          - "--include=promtail-entrypoint.sh"
          - "--exclude=*"

    - name: Copy loki-datasource.yml
      synchronize:
        src: ./grafana-provisioning/datasources/loki-datasource.yml
        dest: "{{ remote_dir }}/grafana-provisioning/datasources/loki-datasource.yml"

    - name: Run the logging ingestion and dashboard
      command:
        cmd: docker compose -f logs.yml up -d
        chdir: "{{ remote_dir }}"
      environment:
        HOST_USER: "{{ ansible_user }}"
