# derived from default config packaged in loki image stored in /etc/loki/local-config.yaml
auth_enabled: false

server:
#  http_listen_port: 3100
  http_listen_port: 3030

common:
  instance_addr: 127.0.0.1
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# sends anonymous but traceable analytics to organization, Loki
analytics:
  reporting_enabled: false
