server:
  http_listen_port: 3031
  grpc_listen_port: 0

positions:
  filename: /tmp/positions-j.yaml

clients:
#  - url: http://localhost:3100/loki/api/v1/push
  - url: http://localhost:3030/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///run/user/1000/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.+)'
        replacement: '$1'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
    pipeline_stages:
      - docker:
          stop_grace_period: 1m  # Allow processing logs for 1 minute after container exit
